### ISSUE TITLE
Markdown 不支持 todo 事项

### ISSUE THREAD

**Issue by light4** [WizTeam/WizQTClient#320]
- [x] 希望能加上 todo 事项的支持
- [ ] 非常喜欢为知笔记，也非常喜欢用 markdown 写东西
- [ ] 希望完善 markdown 支持

**Comment by WizLxn** [comment]
目前有checklist的功能，在markdown笔记中也可以使用

**Comment by light4** [comment]
同样的语法 Markdown 笔记上显示错误。如下：
![test](https://cloud.githubusercontent.com/assets/1318472/8799655/3189069a-2fde-11e5-926b-b4da4ae666bd.png)

**Comment by databill** [comment]
这个功能很有意义，希望可以支持。

**Comment by light4** [comment]
https://github.com/jhollingworth/marked/blob/master/README.md

marked 是支持 taskList 的，希望可以加上。
